name: CI
# Cancel in progress runs if a new one is started
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  test_eslint:
    runs-on: ubuntu-latest
    # Don't allow runs longer than 20 minutes
    timeout-minutes: 20
    strategy:
      matrix:
        node-version: [ 14 ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Cache all node_modules
      - uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
      - name: Install modules
        run: npm install
#       - id: files
#         uses: jitterbit/get-changed-files@v1
#       - run: |
#           for changed_file in ${{ steps.files.outputs.all }}; do
#           echo `Do something with this ${changed_file}.`
#           done
#       - run: |
#           for changed_file in ${{ steps.files.outputs.all }}; do
#           echo `Do something with this ${changed_file}.`
#           npx eslint ${changed_file}
#           done

      - name: Run es lint
        run: |
          echo "${git diff --name-only HEAD }"
          npm run eslint
          
#       - name: Build
#         run: npm run build

#       - name: Test
#         run: npm test
