name: CI
# Cancel in progress runs if a new one is started
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    # Don't allow runs longer than 20 minutes
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "latest"
      # Cache all node_modules
      - uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
          
#       - name : list all files
#         run: ls ${{ github.workspace }}
      - name: Install modules
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
