name: ESLint Check
on: 
  pull_request:
    branches: [main]
    
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
      - run: npm install
      - name: create tmp dir
        run: mkdir ~/tmp/
      - name: get file list
        run: git diff ${{ github.event.pull_request.base.sha }} ${{ github.sha }} --name-only --relative '*.js' > ~/tmp/filelist
      - name: run lint
        run: npx eslint $(cat ~/tmp/filelist)
