name: CI
# Cancel in progress runs if a new one is started
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  test_eslint:
    runs-on: ubuntu-latest
    # Don't allow runs longer than 20 minutes
    timeout-minutes: 20
    strategy:
      matrix:
        node-version: [ 14 ]

    steps:
      - uses: actions/checkout@v2
 
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Cache all node_modules
      - uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
      - name: Install modules
        run: npm ci
   
      - uses: actions/checkout@v1

      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: test eslint  
        run: |
          echo `files ${{ steps.files.outputs.all }}`
          npx eslint ${{ steps.files.outputs.all }}
          done
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
          npx eslint ${changed_file}
          done
