name: reviewdog
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  eslint:
  
    name: runner / eslint
    runs-on: ubuntu-latest
    
    strategy: 
      matrix:
        node-version: [ 14 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          eslint_flags: 'src/'
